### ISSUE TITLE
Server could not find friends Module

### ISSUE THREAD

**Issue by ravipjoshi** [ravipjoshi/beFriends#1]
$ node server.js
internal/modules/cjs/loader.js:638
    throw err;
    ^

Error: Cannot find module '../app/data/friends'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:690:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (C:\Users\Binal\desktop\Bootcamp\HomeWork_RPJ\week-7\beFriends\routing\apiRoutes.js:1:15)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)

**Comment by ravipjoshi** [comment]
Resolved the issue by renaming the file and server started with following message.
$ node server.js
App listening on PORT 8080
Error: ENOENT: no such file or directory, stat 'C:\Users\Binal\desktop\Bootcamp\HomeWork_RPJ\week-7\beFriends\public\index.html'

closing this issue and creating new issue and its relevant branch for above bug called fileNotFound-#2
